version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=martin
      - POSTGRES_PASSWORD=martin
      - POSTGRES_DB=scrapped_reality
    ports:
      - "5432:5432"
  test-runner:
    build: .
    command: pytest /code/tests
    environment:
      - DROP_DATABASE=true
      - USE_DOCKER_CHROME=true
      - DATABASE_URL=postgresql://martin:martin@db:5432/scrapped_reality
      - PYTHONPATH=/code/:$PYTHONPATH
    depends_on:
      - db